export const AUTH_GITHUB_OAUTH_APP_MODULE_OPTIONS_TOKEN = Symbol(
  'AUTH_GITHUB_OAUTH_APP_MODULE_OPTIONS_TOKEN',
);

export const AUTH_GITHUB_OAUTH_APP_INSTANCE_TOKEN = Symbol(
  'AUTH_GITHUB_OAUTH_APP_INSTANCE_TOKEN',
);
